manifest:
  remotes:
    - name: google
      url-base: https://github.com/google
  projects:
    - name: glog
      remote: google
      revision: v0.7.1
    - name: googletest
      remote: google
      revision: main